### ISSUE TITLE
str_limt() is deprecated since the Laravel 5.7

### ISSUE THREAD

**Issue by mayeenulislam** [technovistalimited/shongjukti#10]
As `str_limt()` is been deprecated since the Laravel 5.7, we should not continue with it, because it's blocking the list UI with a fatal error in Laravel 8. Thanks to @mowshana for the bug report

Code in effect is:
https://github.com/technovistalimited/shongjukti/blob/v2.0.1/src/resources/views/attachment-types/index.blade.php#L91

**Comment by captain-burah** [comment]
Duly noted. Thankyou for the intel.
