### ISSUE TITLE
Attachment Type name is not visible when the optional Bengali label is abset

### ISSUE THREAD

**Issue by mowshana93** [technovistalimited/shongjukti#8]
## What is Seen
The Bengali label of a defined Attachment Type is not visible when adding an attachment in Bengali language.

## What is Expected
English label for the attachment should be visible when the Bengali label is absent.

## Steps to Reproduce
1. Add an entry in the Attachment Type scope. Don't provide the Bengali label
2. Now in Attachments in any scope switch to Bengali

There is no label for the attachment

## Possible Working Solution
Here I can suggest some of the possible workaround to solve the issue:

![shonjukti-attachmentTypeModel](https://user-images.githubusercontent.com/11957462/64525813-86c6c380-d323-11e9-908f-3d42cdba47bb.png)
![shonjukti-attachmentModel](https://user-images.githubusercontent.com/11957462/64525814-86c6c380-d323-11e9-8286-faa91187bd37.png)
![attchent-blade-----add-option](https://user-images.githubusercontent.com/11957462/64525815-86c6c380-d323-11e9-96d3-3e6d6360b02b.png)
![attachment-blade-----view-option](https://user-images.githubusercontent.com/11957462/64525816-875f5a00-d323-11e9-8348-3853b0e7bdee.png)

#### attachment blade ----add option

> {{ !empty($attachmentType->name) ? $attachmentType->name : $attachmentType->attachment_type }}

#### attachment blade ----view option
	
> {{ !empty($attachment->name) ? $attachment->name : $attachment->attachment_type }}

####  attachment Type Model-->getAttachmentTypesByScopeKey
>  'name as attachment_type',

#### attachment Model-->getAttachments

> 'attachment_types.name as attachment_type',

**Comment by mowshana** [comment]
`attachment blade ----add option`

> {{ !empty($attachmentType->name) ? $attachmentType->name : $attachmentType->attachment_type }}

	
`	attachment blade ----view option`
	

> {{ !empty($attachment->name) ? $attachment->name : $attachment->attachment_type }}

**Comment by mowshana** [comment]
`     attachment Type Model-->getAttachmentTypesByScopeKey`
>  'name as attachment_type',


`   attachment Model-->getAttachments`

> 	 'attachment_types.name as attachment_type',

**Comment by mayeenulislam** [comment]
Thank you very much for reporting this.
Requesting you to provide a pull request as you have a solution in code. :clap:
